upload

diff --git a/0x05-processes_and_signals/100-process_and_pid_file b/0x05-processes_and_signals/100-process_and_pid_file
--- a/0x05-processes_and_signals/100-process_and_pid_file
+++ b/0x05-processes_and_signals/100-process_and_pid_file
@@ -1,21 +1,24 @@
 #!/usr/bin/env bash
-# This script creates the file /var/run/holbertonscript.pid containing its PID
+# This script creates the file /var/run/myscript.pid containing its PID
 # Displays To infinity and beyond indefinitely
 # Displays I hate the kill command when receiving a SIGTERM signal
 # Displays Y U no love me?! when receiving a SIGINT signal
-# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
+# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
 
-function cleanup() {
-    rm -f /var/run/holbertonscript.pid
+# Function to handle cleanup
+cleanup() {
+    echo "Deleting PID file and terminating..."
+    rm -f /var/run/myscript.pid
     exit 0
 }
 
-trap "echo I hate the kill command; cleanup" SIGTERM
-trap "echo Y U no love me?!; cleanup" SIGINT
+# Trap signals
+trap "echo 'I hate the kill command'; cleanup" SIGTERM
+trap "echo 'Y U no love me?!'; cleanup" SIGINT
 trap "cleanup" SIGQUIT
 
 # Create the PID file
-echo $$ > /var/run/holbertonscript.pid
+echo $$ > /var/run/myscript.pid
 
 # Display the message indefinitely
 while true; do
